export const INIT_STATE = "INIT_STATE";
export const START_ACCESSING = "START_ACCESSING";
export const ACCESS_FAILURE = "ACCESS_FAILURE";

export const CHOSEN_JOB_INDEX = "CHOSEN_JOB_INDEX";

export const UPDATE_JCT_TOKENS = "UPDATE_JCT_TOKENS"
export const UPDATE_JCT_VALUE = "UPDATE_JCT_VALUE"